resources:
  repositories:
    - repository: templates
      type: github
      name: seanyen-msft/rosonwindows_ci
      endpoint: seanyen-msft

jobs:
- template: build.yml@templates  # Template reference
  parameters:
    ros_metapackage: 'ros-melodic-moveit'
